language: java
sudo: false
install:
  - gradle setupCIWorkspace --refresh-dependencies --info
script:
  - gradle build
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
notifications:
  email:
    recipients:
      - email
    on_success: always
    on_failure: always